filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /log/server.log

#output.logstash:
#  hosts: ["logstash01:5044"]
output.elasticsearch:
  hosts: [ "es01:9200" ]

setup.kibana:
  host: "http://kib01:5601"
